### ISSUE TITLE
Content-Type: application/json

### ISSUE THREAD

**Issue by jojoyuji** [diepm/vim-rest-console#1]
how can I set a POST request its content-type?

**Comment by diepm** [comment]
Do you mean specifically setting a value to Content-Type or just submitting a POST request? The latter can be done like

    http://example.com
    POST /form-handler
    key1=value1&key2=value2

**Comment by jojoyuji** [comment]
I mean setting the Content-Type value indeed.

**Comment by diepm** [comment]
I forgot about the content type. Code updated @11094a2. Thanks.

**Comment by jojoyuji** [comment]
thx, working perfectly here!

nice plugin BTW.
