### ISSUE TITLE
curl --connect-timeout

### ISSUE THREAD

**Issue by navicore** [diepm/vim-rest-console#17]
I have network issues with some of the systems I work with and would love to get curl to timeout fast.

As it is, the plugin tries for many seconds (60?) and then displays a timeout error in the output buffer.  If I touch any key during the timeout vim (via tmux) is left in a bad state until I restart.

Anyway to pass args to cURL?  Some obvious trick I'm missing?  If not, would a pull request to tunnel args to cURL be welcome?

Btw, this plugin is GREAT!  I've used it every day for months.  Thx.

**Comment by diepm** [comment]
I don't think there is a way to specify the timeout. It should be quick to add this option. In the mean time, have you tried `C-c` like with shell if it takes too long to response?

**Comment by navicore** [comment]
Ya `C-c` doesn't have an effect (at least under tmux.  I'll try it in other modes.  Thx.

**Comment by navicore** [comment]
I take it back, C-c does let me avoid the bad vim state, my real issue.  Thx.

**Comment by diepm** [comment]
It's great. I'll add the `timeout` option with the next release. Thanks!
