### ISSUE TITLE
Set headers

### ISSUE THREAD

**Issue by dan-silva** [diepm/vim-rest-console#2]
It would be nice if it was possible to set header values in the buffer :) 
It would be very useful when sending requests that must be authenticated with the `Authorization` header.

**Comment by korin** [comment]
:+1:

**Comment by diepm** [comment]
Ye, I'll add it.

**Comment by diepm** [comment]
Being able to set headers in buffer is added @7fa0a9b5. Thanks.

**Comment by korin** [comment]
@diepm thanks a lot

**Comment by dan-silva** [comment]
Thank you!
