### ISSUE TITLE
Make multiple http request inside a REST request block

### ISSUE THREAD

**Issue by q12321q** [diepm/vim-rest-console#21]
When I look at _your sample.rest_ you repeat _http://localhost:9200_ many times. I'm lazy. What I would like to be able to do is to write the host just one time and then have multiple rest requests with the same host and headers:
```
# Submitting a form.
http://localhost:9200

Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==

GET /_cat/nodes?v
POST /testindex/testtype
{
    "name": "some name",
    "value": "some value",
    "date": "2015-01-01"
}
GET /testindex/_search?pretty
#end of the block
```

When I trigger <C-j> on the POST or its body it'll execute the POST request with the host and header defined above.

What do you think?

**Comment by q12321q** [comment]
Sorry It duplicates the pull request (Allow the definition of global host and headers)...

**Comment by diepm** [comment]
Yup, I'm lazy, too. That's why this feature is slow to come but it's here anyway! Let's type less ;)
