### ISSUE TITLE
POST not included as curl verb

### ISSUE THREAD

**Issue by shanesmith** [diepm/vim-rest-console#25]
The plugin intentionally omits the `-X` curl flag when the verb is POST, which is causing me issues with a certain POST api that doesn't require data in the body, in which case the curl command from VRC will effectively be a GET.

Easy to patch, but I was first wondering why this was done?

https://github.com/diepm/vim-rest-console/blob/master/ftplugin/rest.vim#L294

**Comment by diepm** [comment]
I tried to avoid using `-X POST` (according to `curl` man page) but forgot that without the request body (`--data`), `curl` would treat it as `GET`.

We have a couple options.

+ Could also consider the request body when returning the verb; use `-X POST` for empty body, or
+ Always add the empty data `--data ''` for `POST`. I'm not sure how `curl` behaves when both `--data` and `--data-binary` are used.

**Comment by shanesmith** [comment]
Reading the curl man page I don't think you necessarily need to avoid using `-X POST`, it rather says that you "normally don't need this option" since other options will internally set the verb. In my opinion I don't think explicitly setting `-X` would be an issue.

Otherwise, if you still don't want to explicitly set it, I think your first option would be a little cleaner.

**Comment by diepm** [comment]
I think it should be fine to always use `-X POST` since `-X POST --data 'f1=v1'` is still a true POST request anyway.

**Comment by shanesmith** [comment]
Thanks!
