### ISSUE TITLE
allow to define split position

### ISSUE THREAD

**Issue by juanolon** [diepm/vim-rest-console#28]
hey, nice plugin. 
but there is no way to change, which split should be open. horizontal/vertical split. any change to get that feature? :)

**Comment by diepm** [comment]
Yeah. I'll include it in the next release. Thanks.

**Comment by diepm** [comment]
You can now use option `vrc_horizontal_split` for horizontal split.

**Comment by juanolon** [comment]
nice! that was fast 👍
