### ISSUE TITLE
allow disable mapping

### ISSUE THREAD

**Issue by korin** [diepm/vim-rest-console#3]
Right now there is no option to disable mapping, any plans to change it?

**Comment by diepm** [comment]
Can you describe the scenario of what you want to do?

**Comment by korin** [comment]
I just want to disable default mapping. Right now user can change default mapping key but is forced to use default mapping 
```
    execute 'vnoremap ' . triggerKey . ' :call VrcQuery()<CR>'
    execute 'nnoremap ' . triggerKey . ' <Esc>:call VrcQuery()<CR>'
    execute 'inoremap ' . triggerKey . ' <Esc>:call VrcQuery()<CR>'
```

I created a pull request to show you what I mean. Default behavior stays the same, but default mapping can be disabled. I think it's polite to allow user fully control mapping.

**Comment by diepm** [comment]
You're right. That makes sense. I'll update the docs, thanks for fix :-)

**Comment by korin** [comment]
thanks
