### ISSUE TITLE
Serialized JSON in GET request

### ISSUE THREAD

**Issue by chaucerbao** [diepm/vim-rest-console#33]
[StrongLoop LoopBack REST APIs](https://docs.strongloop.com/display/public/LB/Querying+data#Queryingdata-Using"stringified"JSONinRESTqueries) can use serialized JSON objects in their query string.

```
/api/example?filter={"where":{"id":1234}}
```

Brackets in cURL are for globbing, so a [solution](http://stackoverflow.com/questions/25435798/how-to-curl-post-with-json-parameters) is to include the `-g` option to disable globbing.

Is there (or can we have) an option to append arguments to the cURL command, either globally or as-needed?

Other solutions are welcome as well.

**Comment by diepm** [comment]
Do `{` and `}` must present or can they be url-encoded? For example, if I have this request block,

```
http://example.net
GET /api/example
filter={
  "where": { "id": 1234 }
}
```

VRC generates this GET request

    GET /api/example?filter=%7B%20%20%22where%22%3A%20%7B%20%22id%22%3A%201234%20%7D%7D

Does it work in your scenario?

**Comment by chaucerbao** [comment]
This works!

For some reason, I thought that syntax was for submitting data in the request body rather than the query string.

**Comment by diepm** [comment]
Great! To include the request body for GET request, we need to explicitly enable the option `vrc_allow_get_request_body`.
