### ISSUE TITLE
Define variable

### ISSUE THREAD

**Issue by tdroxler** [diepm/vim-rest-console#34]
Hi,

amazing tool that I use daily at work and thus starting to wanted new features :-)

So it's not really an issue, but is it possible to to define variables? For examples to be able to do something like this:

```
http://localhost:1234
--
var city = blablabla
var street = lolalo
--
GET /city/$city/street/$street
--
GET /city/$city/street/$street/number/3
```
So when I want to make my call on another city/street, I don't need to change it in every endpoints.

Thanks, Cheers

**Comment by diepm** [comment]
I think it's possible. Using `$` might be an issue since it may appear in the uri path. Probably `:` is a better choice. Something like

```
# Global
http://host

var city = some value
var zip = 12345
--

--
GET /zip/:zip/city/:city
```

I guess supporting global variables is good enough; local variables don't seem to be very helpful.

**Comment by tdroxler** [comment]
Ok thanks, I'll see if I can hack the code.

**Comment by tdroxler** [comment]
So I did a little something in #35 First time I wrote VimL, hope it's ok

**Comment by diepm** [comment]
Cool. Thanks!
