### ISSUE TITLE
Issue with DELETE request messing up cursor position

### ISSUE THREAD

**Issue by mikeLspohn** [diepm/vim-rest-console#37]
Anytime I try to run a DELETE request it jumps the cursor down under my status bar and things get all wonky and I have to ctrl-c to even be able to `:q`. Here's an example request

```
http://localhost:3000
DELETE /users/jon
```

All my other requests always work great and cause no problems, but DELETE is causing an issue every time I try it. It still works and executed the request, but I have to quite and jump back in to continue on.

I'm on OSX 10.11.5

Vim 7.4.1054

**Comment by mikeLspohn** [comment]
It seems to be working fine for me now. Not sure what fixed it, but it works fine now 😄  Thanks for the awesome plugin!

**Comment by diepm** [comment]
Great to hear it's working now. Please let me know if it happens again :-)

**Comment by mikeLspohn** [comment]
So the issue was if the request hangs and timesout, then it causes that issue. So it was more an issue with my request, but just for the heads up it seems like a request that times out causes this issue. This is probably safe to close.

**Comment by diepm** [comment]
I've tried to reproduce your scenario but unsuccessful. However, I notice that while waiting for the response, VRC is irresponsive. If we type something during this time, funny things happen, which is not abnormal for a terminal app (it doesn't happen with MacVim).

There are `vrc_connect_timeout` and `vcr_max_time` that might help reduce the waiting time.

**Comment by mikeLspohn** [comment]
Ah ok, thanks for clearing that up for me. Sounds like normal behavior then.
