### ISSUE TITLE
Feature request: Add ability to pass raw curl options

### ISSUE THREAD

**Issue by minhajuddin** [diepm/vim-rest-console#39]
Thanks for creating this awesome plugin :+1: 

I would send you a pull request for this but I am not good at viml

Since this plugin uses curl, it would be great if there was a way to pass options directly to curl, for instance I was trying to find a way to make a multipart POST and didn't find a way to do that using VRC. curl however supports this. If we could add a way to pickup the text after a curl-raw in the request line or before request line, something like below

```
http://api.localhost:4444
curl-raw --form 'file=@/tmp/upload'
GET /
```

Thanks again for creating this plugin :)

**Comment by diepm** [comment]
Sorry for the late reply. For some reason I didn't notice it's a new issue.

It's actually a good idea that VRC can pass raw curl options thru. This way, VRC is more flexible. However, flexibility comes with its cost (code complexity, stability, maintainability...). I'll try to see if there are any good options for us.

**Comment by minhajuddin** [comment]
Thanks for the response. I completely understand what you are saying :smile: 
Like you said, It would be awesome to have this feature :smile:

**Comment by umitkablan** [comment]
Hi, 

Any progress about that? I would like to pass custom --cacert to curl and other uses would be possible once that feature is implemented. Do you think to?

**Comment by diepm** [comment]
I've already had a plan for it. It's pretty simple but should get the job done. The idea is that curl options can be specified in the header sections prefixed with `-` or `--`.

**Comment by umitkablan** [comment]
Thanks for your efforts!
Btw, I discovered that `.curlrc` is being read by curl command line program - so I think we can also make use of that feature as a side/fast solution. Though I believe setting them in `vrc` file would be more obvious.

**Comment by mikedfunk** [comment]
+1

**Comment by diepm** [comment]
This feature is added with v3.0.0.

**Comment by juan-gomez-hub** [comment]
Excuse my lack of knowledge, but could you please upload an example of how to make a multipart/form-data request? I can't find the way.
