### ISSUE TITLE
Unformatted responses when curl command is shown

### ISSUE THREAD

**Issue by eemp** [diepm/vim-rest-console#42]
When I set just the `let g:vrc_show_command = 1` configuration option without changing the `vrc_auto_format_response_*` defaults, JSON responses that I receive are unformatted.  The response headers include `Content-Type`.  Without setting the `vrc_show_command` option, the response is formatted as expected.

I did not find anything in the README regarding this but I apologize if I overlooked something.  I just updated the plugin before posting this.

**Comment by diepm** [comment]
I think it's fixed now. Please check. If all good, please close this issue. Thanks!

**Comment by eemp** [comment]
Yes! Thanks a lot!!
