### ISSUE TITLE
`-k` option causes cURL to fail on macOS

### ISSUE THREAD

**Issue by chaucerbao** [diepm/vim-rest-console#43]
Since the last update, it looks like the plugin [automatically includes](https://github.com/diepm/vim-rest-console/blob/master/ftplugin/rest.vim#L413-L415) the `-k` flag if the URL has **https**.

On Mac, it produces:
> curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect

Running the cURL command without the `-k` option returns the expected results.

Is there a way to disable the automatic inclusion of that option?

**Comment by diepm** [comment]
Could you enable the debug mode (`let g:vrc_debug=1`) , make a request, and paste the debug message here (`:mes`)?

**Comment by diepm** [comment]
Nvm. I've just pushed the fix. Could you retest?

**Comment by chaucerbao** [comment]
Looking good.

Thanks for the fix!
