### ISSUE TITLE
vrc_auto_format_response_enabled no longer available?

### ISSUE THREAD

**Issue by richox** [diepm/vim-rest-console#45]
i found it removed in commit:

    commit ac3f383b0953041145634a58c00ad090b93220dc
    Author: diepm <diepm@mbp.local>
    Date:   Fri May 26 00:43:35 2017 -0500

        Support raw cUrl options

but why? this option is very important for debugging rest apis.

**Comment by diepm** [comment]
That option is still available. I think it's a bug related to this issue https://github.com/diepm/vim-rest-console/issues/44. Fix just pushed. You can check it again.
