### ISSUE TITLE
Auto Formatting Response Doesn't Work

### ISSUE THREAD

**Issue by marad** [diepm/vim-rest-console#47]
I get unformatted server response. After a brief debugging I discovered that in line 640 there is:

```vimscript
        let formattedBody = system(
          \ formatCmd,
          \ getline(emptyLineNum, '$')
        \)
```

The problem is that `getline` function returns an array containing headers and response.  I've tried setting it to `getline(emptyLineNum, '$')[-1]` and this makes output formatted but then headers section is invisible.

**Comment by diepm** [comment]
Do you still have (or be able to reproduce) the problematic response? The output from the beginning up to first few characters of the body would be helpful.

**Comment by marad** [comment]
@diepm Well I don't have it at hand, unfortunately. Do you assume there was something wrong with the response? I had this problem with every response (simple JSON responses). 

The only unusual thing was that Content-Type was set to application/XYZ+json. But I believe that I tried the client with usual REST services returning Content-Type as application/json and the result was the same.

**Comment by diepm** [comment]
Do you have VRC include the response header along with the response body?

**Comment by marad** [comment]
I didn't have the option set at first. Then the headers were visible and body wasn't formatted.

After adding this fix at the top the body gets formatted and headers disappeared. Adding right option (-i if I recall correctly) makes headers visible again.

Was visible headers without the option set a bug?

**Comment by diepm** [comment]
Usually without `-i` (or `--include`), there shouldn't be response headers. It's weird that headers are included with those options disabled since it's cUrl behaviors.

Without any options (`g:vrc_curl_opts` not set), the response is something like

```
http://localhost:9200
GET /test/_mappings
```

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   213  100   213    0     0  10630      0 --:--:-- --:--:-- --:--:-- 11210
{"test":{"mappings":{"product":{"properties":{"name":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"sku":{"type":"text","fields":{"keyword":       {"type":"keyword","ignore_above":256}}}}}}}}
```

When I add `-sS` to surpress the progress, I get only this.

```
{"test":{"mappings":{"product":{"properties":{"name":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"sku":{"type":"text","fields":{"keyword":       {"type":"keyword","ignore_above":256}}}}}}}}
```

When adding `-i` to include the headers, I get the formatted body.

```
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 213

{
  "test": {
    "mappings": {
      "product": {
        "properties": {
          "name": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
                ...
```

You can enable the debug mode (`let g:vrc_debug=1`) and check the executed cUrl command after each request by `:mes`.

**Comment by marad** [comment]
I'm a bit confused now. I removed my hack to try and test all you are asking. Now everything seems to work as expected. I'm not sure what caused the problem in the first place. I believe that updating to the newest version fixed it and now it seems to work just fine.

Sorry for wasting your time on that.
