### ISSUE TITLE
Undefined variable: curlOpts

### ISSUE THREAD

**Issue by bcicen** [diepm/vim-rest-console#49]
Using fresh install of plugin using Vim 8.0, I get the below error on trigger with a single-line block:

```
http://localhost:8080 POST /data {"ids": ["25f7c2e5"] }
```

```Error detected while processing function VrcQuery[19]..<SNR>67_RunQuery:
line   34:
E121: Undefined variable: curlOpts
E116: Invalid arguments for function vrc#opt#DictHasKeys(curlOpts, ['-i', '--include']) })
E116: Invalid arguments for function <SNR>67_DisplayOutput
```

Line-separating the host, method, and payload resolves the error.

If the above single-line syntax is not supported, should the README examples be updated to reflect this?

**Comment by diepm** [comment]
Sorry for the confusion. It's due to the wrong markdown syntax. Should be fixed now.

**Comment by bcicen** [comment]
thanks @diepm!
