### ISSUE TITLE
how to use this plugin when curl requires '-u' (username password)

### ISSUE THREAD

**Issue by pinggit** [diepm/vim-rest-console#59]
in my setup I need to give curl a username and password to access those APIs.
how to use this plugin in this context?

**Comment by diepm** [comment]
The basic option is `-u username:password`. You have a few place to set this option.
* In the `rest` file, global section.
* In the request block.
* In `g:vrc_curl_opts` but this will affect all your requests.
You can check the executed curl command by `let g:vrc_show_command = 1`.

**Comment by pinggit** [comment]
this is great, how to get this fix to my local clone?

**Comment by diepm** [comment]
It's already merged. You can reinstall or just go to `vim-rest-console/` and do `git pull`.

**Comment by pinggit** [comment]
got it, it works! thanks.
