### ISSUE TITLE
PUT and --data-binary

### ISSUE THREAD

**Issue by manatarms** [diepm/vim-rest-console#69]
I'm trying to have a PUT request use the --data-binary curl option, but it seems the plugin seems to be adding --data and putting the flag as the data. See example below
# Request
```
# Global scope.

let g:vrc_curl_opts = {
  \ '--data-binary': '~/Desktop/img.jpg'
\}

--
--


PUT /url/img
--data-binary: '@~/Desktop/img.jpg'

```

# Raw curl
```
curl -X PUT --data '--data-binary @~/Desktop/img.jpg' '/url/img'

```

How would I tell the plugin to use data-binary instead of data?

**Comment by diepm** [comment]
Can you do

```
PUT /url/img
@~/Desktop/img.jpg
```

and can you use POST instead of PUT?

**Comment by manatarms** [comment]
```
PUT /url/img
@~/Desktop/img.jpg\
```
This worked. Thank you. I'm happy to make a PR to update docs, if PRs are welcom.

**Comment by diepm** [comment]
Yes, please. Thanks!
