### ISSUE TITLE
Allow global variable to pull in data from environment variables

### ISSUE THREAD

**Issue by jrop** [diepm/vim-rest-console#74]
It would be nice if I could pull in, say for example, an API key from an environment variable, and set it in the global section:

```
http://dev.virtualearth.net/REST/v1
-s
-i
key=$BING_MAPS_KEY
--

--
GET /Locations/40.54377,-105.02996?key=:key

--
GET /Elevation/List?points=40.54377,-105.02996&key=:key
```

It seems that this would need to be a new feature added to `ParseVals`?: https://github.com/diepm/vim-rest-console/blob/9371b810e4a037c063df76380ebd2803550506d5/ftplugin/rest.vim#L241

**Comment by jrop** [comment]
I created #75 which supports this

**Comment by diepm** [comment]
Merged.
