### ISSUE TITLE
Authenticate with OAuth2

### ISSUE THREAD

**Issue by axpira** [diepm/vim-rest-console#77]
Hi,

Can I authenticate in some rest API using OAuth2?

Thanks

**Comment by diepm** [comment]
If you can do that with cUrl, then more likely yes since VRC uses cUrl under the hood.

**Comment by tdroxler** [comment]
yep you can, I had to do it few days ago. Just add:
 ```
Authorization: Bearer MYSUPERLONGTOKEN
```
in the header section. we can close this issue IMO

**Comment by diepm** [comment]
Thanks for confirming, @tdroxler
