### ISSUE TITLE
Nice trick to enable syntax highlighting for the output buffer

### ISSUE THREAD

**Issue by mjakl** [diepm/vim-rest-console#8]
This is of course no bug, but a suggestion for a _Tips'n'Tricks_ section of the documentation.

If the appropriate ftplugin is installed, it is very easy to enable output syntax highlighting (especially for JSON) with this in your `.vimrc`:

```viml
let b:vrc_output_buffer_name = '__VRC_OUTPUT.json'
```

Alternatively, it might be possible to set it per request buffer using a special modeline (requireing [let-modeline](http://www.vim.org/scripts/script.php?script_id=83)):

```viml
# vim: let b:vrc_output_buffer_name = '__VRC_OUTPUT.json'
```

Thanks, VRC is a great idea!

**Comment by diepm** [comment]
Nice. I'll update the docs to add a TnT section. I have some ideas to add to VRC but some can be done now as "tricks." Thanks.

**Comment by mjakl** [comment]
Small addtion: using `let b:vrc_output_buffer_name = '__VRC_OUTPUT.json'` works well for console Vim, but for the GUI version (at least for MacVim), we need to use `let g:vrc_output_buffer_name = '__VRC_OUTPUT.json'`

**Comment by diepm** [comment]
@mjakl I don't have syntax highlighting for json (it uses javascript by default) but I can do the trick with XML like `:let b:vrc_output_buffer_name = '__VRC.xml'` and this works. Are you setting the buffer name when you're in the VRC buffer? Since it won't take effect if you're in the output buffer.

**Comment by mjakl** [comment]
I've set the variable in my `.vimrc`. It worked using `b:vrc_output_buffer_name` in the consloe version of Vim, but not in MacVim. Using `g:vrc_output_buffer_name` worked in both versions.

**Comment by mjakl** [comment]
The trick has been included in the READM. Closing.
