### ISSUE TITLE
Reformat output response by using json_pp

### ISSUE THREAD

**Issue by thanhvang99** [diepm/vim-rest-console#92]
Using json_pp to make format output response friendly.
Install json_pp for MacOS: brew install json_pp
After installation json_pp, modify code at line 747 in file rest.vim like that:

![image](https://user-images.githubusercontent.com/41734341/93590574-f52f6e80-f9d8-11ea-8883-a2aae382192f.png)

Hope you enjoy it!

**Comment by emaniacs** [comment]
i create pr for feature like this.
#93
